### ISSUE TITLE
Expression with multiple observables?

### ISSUE THREAD

**Issue by SkytAsul** [Osmerion/Quitte#3]
I am trying to make an expression using two observables (basically, it's a `min(observable1, observable2)`) but I can't find my way with Expressions.
I thought I had to use `SimpleIntExpression.of(...)` but there are only functions to get expressions derived from one observable value.
What am I missing?

**Comment by TheMrMilchmann** [comment]
The `<...>Expression.of(...)` methods are utility methods to make simple transformations a little easier. If you need anything more complex, you have to extend the expression. Anonymous classes are one way to do this:

```java
    public static SimpleIntExpression min(ObservableIntValue a, ObservableIntValue b) {
        return new SimpleIntExpression() {

            {
                this.addDependency(a);
                this.addDependency(b);
                this.invalidate();
            }

            @Override
            protected int recomputeValue() {
                return Math.min(a.get(), b.get());
            }

        };
    }
```

The JavaDoc for expressions needs some improvement so here's a very short summary:
- `get` and `getValue` are pretty self-explanatory.
- _Dependencies_ are the observables that an expression is using during its calculation. You can use `addDependency`/`removeDependency` to - well - add, or remove dependencies. This takes care of setting up the listeners for you.
- Implement `recomputeValue` to calculate the value for the expression.
- To tell the expression to recompute the value, use `invalidate`. In the example above, this is done right after registering the dependencies.
- Unless you are writing a very complex expression with dynamic dependencies, following the example above will probably cover all of your use cases.

Also, I noticed that some stuff that shouldn't be exposed is currently exposed by expressions. This will be fixed in a future release. Please do not override or access any methods or fields other than the ones mentioned above.

**Comment by SkytAsul** [comment]
Alright thanks for your detailed reponse, that's what I needed to know!
I really like to work with your library, keep up the good work :)
