### ISSUE TITLE
Unbinding not bound properties throw IllegalStateException

### ISSUE THREAD

**Issue by SkytAsul** [Osmerion/Quitte#7]
Calling `WritableProperty#unbind()` on unbound properties throws IllegalStateException. https://github.com/Osmerion/Quitte/blob/b7c247b2e7acccff65eebc8376b83abf17613eef/modules/quitte/src/main-generated/java/com/osmerion/quitte/property/AbstractObjectProperty.java#L224
Whereas the javadoc specifies this:
> If this property is unbound, this method does nothing.

That is pretty weird, I don't know what is supposed to be the real behavior.

**Comment by TheMrMilchmann** [comment]
Thanks, for the report. This is indeed a problem and I will take care of it in the next update. I'll also have to reconsider whether `bind` and `unbind` methods should throw. Currently, I'm tempted to leave the implementations as-is and adjust the JavaDoc because throwing seems like a good way to prevent subtle bugs.

**Comment by SkytAsul** [comment]
In this case, may you add a dumb method like "unbindSilently" (not sure about the name) that unbinds if the property is bound or else fails silently?

**Comment by TheMrMilchmann** [comment]
The issue here is that your code should (ideally always) know if a property is bound. Not knowing how a property is used indicates it's probably a good idea to refactor the code. In rare cases where it's actually necessary to unbind a property without knowing its state, you can guard against errors using an `isBound` check already. Adding a `unbindSilently` method would promote this behavior which I'm advising against using.
